version: '3'

services:
  web:
    container_name: web
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: php:8.1-apache
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80